env : "dev"
storage_path: ./storage/schedule.db
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
storage:
  host: localhost
  port: 5432
  database: schedule
  username: postgres
  password: postgres