env : "dev"
storage_path: ./storage/schedule.db
google_config:
  google_creds_path: schedule/internal/gglapi/studentsbot-414221-88a1d65d3976.json
  spreadsheets_id: 1tOJucauaVM3FnNpSHx9CiW01-YC3xITRsrTrQSahbCU
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
storage:
  host: localhost
  port: 5432
  database: schedule
  username: postgres
  password: postgres