version: '3'

services:
  app:
    build: ./app
    container_name: students_bot
    command: python bot.py
    env_file:
      - ./app/.env
    environment:
      - TZ=${TZ}
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - my_network
  db:
    container_name: pg_db_container
    image: postgres:16-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=students_bot_db
    ports:
      - "5433:5432"
    networks:
      - my_network
  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    env_file:
      - ./app/.env
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
#      - PGADMIN_CONFIG_SERVER_MODE="False"
#      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
#      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:80"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge