version: '3'

services:

  app:
    build: ./app
    container_name: bot_cont
    command: python bot.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    expose:
      - 8099
    depends_on:
      - db
    networks:
      - prod_network
    ports:
      - "8099:8099"

  db:
    container_name: pg_db_cont
    image: pgvector/pgvector:pg16
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=students_bot_db
      - SCHEDULE_DB=schedule
      - VECTOR_DB=vector_db
    ports:
      - "5433:5432"
    networks:
      - prod_network

  schedule:
    build: ./schedule
    image: schedule-app:prod
    container_name: schd-app
    networks:
      - prod_network
    depends_on:
      - db
    expose:
      - 8090
    ports:
      - "8090:8090"

  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_LOGIN}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - prod_network

networks:
  prod_network: