version: '3'

services:
  app:
    build: ./app
    container_name: st_bot
    command: python bot.py
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - my_network
  db:
    container_name: pg_db_container
    image: pgvector/pgvector:pg16
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=students_bot_db
      - VECTOR_DB=vector_db
    ports:
      - "5433:5432"
    networks:
      - my_network
  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    env_file:
      - ./app/.env
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_LOGIN}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge