version: '3'

# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d
services:
  app:
    build: ./app
    container_name: students_bot
    command: python bot.py
    env_file:
      - ./app/.env
    environment:
      - DATABASE_URL=postgresql://postgres:Ma!azD9e@db:5432/students_bot_db
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ma!azD9e
      - POSTGRES_DB=students_bot_db
    ports:
      - "127.0.0.1:5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=malakanton@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=isp123vpoz
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555