version: '3'

services:

  app:
    build: ./app
    container_name: bot_cont
    command: python bot.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - bot_db
    networks:
      - prod_network

  bot_db:
    container_name: pg_db_cont
    image: pgvector/pgvector:pg16
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=students_bot_db
      - VECTOR_DB=vector_db
    ports:
      - "5433:5432"
    networks:
      - prod_network

  schedule:
    build: ./schedule
#    image: schedule-app:local
    container_name: schd-app
    networks:
      - prod_network
    depends_on:
      - schedule_db
    expose:
      - 8080
    ports:
      - "8080:8080"

  schedule_db:
    image: postgres:16
    container_name: schd-db
    volumes:
      - ./schd-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres4344
      - POSTGRES_DB=schedule
    ports:
      - "5432:5432"
    networks:
      - prod_network

  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - schedule_db
      - bot_db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_LOGIN}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - prod_network

networks:
  prod_network: