version: '3'

# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d
services:
  app:
    build: ./app
    container_name: flask_azz_yt
    command: python bot.py
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://az_user:az_psw@db:5432/az_dbname # путь до бд, см. db service
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ma!azD9e
      - POSTGRES_DB=students_bot_db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=malakanton@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=azzrael_code_yt # если сменить здесь, то нужно удалить контентер
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 # чтобы не было косяков с nginx лушче в одну сеть с app
      - PGADMIN_LISTEN_PORT=5555